### ISSUE TITLE
Add a control to hide/show the voltmeter

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#106]
On Thursday @ariel-phet said we are planning to add a checkbox above "Field Lines" that allows you to hide/show the voltmeter.

@ariel-phet can you please prioritize/schedule/delegate?

**Comment by mbarlow12** [comment]
@ariel-phet, I finalized this addition as it has been brought up a few times in the descriptions/alerts discussion. Let me know what next steps are necessary for review.

**Comment by samreid** [comment]
Co-assigning to @zepumph and @samreid to review the phet-io instrumentation of the new control.

**Comment by zepumph** [comment]
I'm seeing a bit of a bug. 

`faradaysLaw.faradaysLawScreen.view.voltmeterNode.opacityProperty` is only controlling to console, not the wires to the lightbulb, but `faradaysLaw.faradaysLawScreen.view.voltmeterNode.visibleProperty` is toggling the visibility of everything. 

I see a listener like: 
```
+    this.addChild( voltmeterWiresNode );
+
+    model.showVoltmeterProperty.link( function( showVoltmeter ) {
+      voltmeterNode.visible = showVoltmeter;
+      voltmeterWiresNode.visible = showVoltmeter;
+    } );
```
In the `ScreenView.js`, so perhaps we want to do that for opacity as well. In `Node.js` I see that opacity is an event that we can listen to (in `Node.setOpacity`):
```
        this.trigger0( 'opacity' );
```

So I'll rig something up off of that.

**Comment by zepumph** [comment]
Implemented above. Now that I've done this, I think it is a little bit sketchy. Basically we want to treat these two Nodes as a single Node, and instead of creating a single node for them, we are just linking up all the properties that we care about to make sure they stay in sync (opacity and visibility). I didn't, though, do this for pickability, since it is never pickable. In the future if we ever add another public NodeIO sub property, we would have to manually link these two. Instead I recommend instrumenting via composition, and creating a new Node that holds the VoltmeterNode and its wires, and passing the "voltmeterNode" tandem to that so that it is more obvious what is going on. Let me give that a try.

**Comment by zepumph** [comment]
I added `VoltmeterAndWiresNode` above, and I think I like it. Although the creation of the new type added some complexity, it simplified the ScreenView, and @mbarlow12's checkbox, which I like. It also seems more robust. @samreid will you review and see if you feel like the way I used tandem is suitable. Right now we are instrumenting `VoltmeterWithWiresNode` with the tandem `voltmeterNode`, and then passing that same tandem (unmodified with `createTandem`) into `VoltmeterNode` so that the label can look like a direct decedent to the "voltmeterNode".

**Comment by zepumph** [comment]
Today during phet-io meeting, @chrisklus, @samreid, and I noticed that the checkbox is titled "Volt Meter," but noticed that everywhere in the code, and often on the internet that it is one word: "Voltmeter." We think that we should change the display to be a single word.

Furthermore this string is not yet in the strings files for translation, that will need to be done before republication. 

Assigning to myself to implement these changes, and tagging @mbarlow12 to note that I will be working in this repo.

**Comment by zepumph** [comment]
Voltmeter is now translatable, @samreid please review.

**Comment by samreid** [comment]
The commit https://github.com/phetsims/faradays-law/commit/110108e109f90e4579a9cce9d887d76e80f710df looks great, thanks @zepumph.  It looks like everything in this issue is complete, closing.
