### ISSUE TITLE
Apply consistent documenting strategies to instanceDocumentation strings

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#111]
All strings in this sim that are public facing over the phet-io api should follow the conventions laid out in https://github.com/phetsims/phet-io/issues/1334.

**Comment by zepumph** [comment]
@chrisklus please review. I'm no grammar expert, but do these seem alright to you?

**Comment by chrisklus** [comment]
Looks really good @zepumph.

I made a couple nitpicky changes: "Set whether..." to "Sets whether..." to stay consistent with "Indicates whether...", "Determines whether..." etc, since the thing itself is doing the setting, not the user. And "Property that controls whether...", to "Controls whether..." to match the above cases that don't restate the type at the beginning of the description.
