### ISSUE TITLE
Bar can be moved into coil using keyboard nav

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#113]
A sound design is being done for this sim, and while testing a prototype, we noticed that some odd things can happen when moving the magnet using the arrow keys.  The screen shot below is an example.  In this case, the magnet was moved all the way to the right (against the boundary), and then the left arrow key was hit a couple of time.

![image](https://user-images.githubusercontent.com/3082831/43029318-ab1130d2-8c42-11e8-8feb-9d5fdb9dbd88.png)

The magnet stopped in a place that made it look like it was embedded in the coil.

@mbarlow12 - it was suggested during the review meeting that this be assigned to you.  Please assign to the appropriate person if it isn't you.  Also, please let us know if keyboard nav for this sim is still in an early phase and, if so, we won't log more issues until it's further along.

Tagging @mikewinters10 so that he's aware of the state of this (since he is the main person working on the sound design prototypes).

**Comment by mbarlow12** [comment]
@jbphet thanks. I think @zepumph referenced this bug in another issue, but I'm having trouble finding it.

I've refined the keyboard interaction a good bit in the `jump` branch, but I'll double check that this issue is handled before merging with master. Once the descriptions and documentation is finalized I'll make the merge.

**Comment by mikewinters10** [comment]
I think that the issue may be related to the fact that in keyboard navigation, the position of the magnet always snaps to an integer and will also skip over integers. For example, a horizontal movement might look something like this:

(112, 340)
(115, 340)
(118, 340)
(121, 340)

If the boundary of the coil was (120, 340), this would overshoot the position of the coil by 1. When the mouse is being used, these position values are floats and integers only occur when the magnet hits the coil. 

Fixing this bug is important for the sonification. The sound of hitting the coil is only triggered when the magnet's position stops at the true coil boundary.

**Comment by mikewinters10** [comment]
@mbarlow12 and @jbphet, has this issue been resolved? If so, please let me know and I can finalize the sonification wrapper.

**Comment by jbphet** [comment]
I just tried it on master, and it seems better, but not 100% better.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/3082831/43850515-657e2c70-9af5-11e8-9a34-a731591acc9c.png)

@mbarlow12 - what's the likelihood of getting this resolved soon?
@mikewinters10 - would the behavior shown in the screenshot above be good enough for the purposes of the next sonification wrapper release?

**Comment by mbarlow12** [comment]
@jbphet @mikewinters10 This looks to me like it's fixed in master. Can one of you confirm?

**Comment by jbphet** [comment]
The behavior now looks great!  I don't see any commits referenced to this issue, so I haven't reviewed the code.  Thanks for the fix @mbarlow12.  Closing.
