### ISSUE TITLE
Changes to text description if the bar magnet is touching the coil

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#138]
If the magnet is touching a coil, then the text description in the PDOM can just say it's touching the top or bottom (and the rest of the description removed).

For example, currently if the magnet is touching the 4 loop coil, the description states:
> "\<h3\>Bar Magnet\</h3\> The bar magnet is at the center of the Play Area. In 4-loop coil. ..."

If the magnet is touching the top left or top right of the coil, the description should say:
> "\<h3\>Bar Magnet\</h3\> Bar magnet touching the top of 4-loop coil..."

If the magnet is touching the bottom left or bottom right of the coil, the description should say:

> "\<h3\>Bar Magnet\</h3\> Bar magnet touching the bottom of 4-loop coil..."

These changes should be applied to the 2-loop coil scenario as well.

Based on discussion from #130 .

**Comment by terracoda** [comment]
@jhung , I have made some comments in issues #131, #134 that might be related to this description, and the earlier discussion in #130. I feel, even tangentially in terms of description style this issue is related to suggestions for the circuit made in issue #133.

There are several open issues about the description of the magnet and the coils, some are the description in the PDOM (like this one) and some might be alerts. In issue #131, I think I laid out examples for both. @jhung, could you review issue #131. I'm not sure you have seen that issue yet.

**Comment by jhung** [comment]
We should put this on hold pending discussions regarding an explicit magnet pick-up and release interaction.

**Comment by jhung** [comment]
No longer applicable with revised designs. Closing this issue.
