### ISSUE TITLE
Conduct interviews to get input on voltage sound behavior

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#178]
In #163 we have been working to add a sound generator to represent the amount of voltage that is being produced by moving the magnet near and through the coils.  We've been trying out two options, one in which the visibility of the voltmeter affects the sound that is being produced and one where the sounds are the same regardless of the voltmeter's visibility.  We'd like to get some outside input, probably via interviews, to help us figure out which way to go on this.

I've published a dev version that supports a query parameter to switch between the two modes.  The query parameter is `voltmeterVisibilityAffectsSounds`, and here are links where it is used in context.

- Sound varies with voltmeter visibility: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.61/phet/faradays-law_en_phet.html?voltmeterVisibilityAffectsSounds=true
- Sound always the same (ignores voltmeter visibility): https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.61/phet/faradays-law_en_phet.html?voltmeterVisibilityAffectsSounds=false

Assigning initially to @emily-phet, and I think she plans to involve @BLFiedler.

**Comment by emily-phet** [comment]
@BLFiedler - putting this on your radar for discussion next week. We have some specific questions re the sound, and will need some interviews to get those answered.

**Comment by BLFiedler** [comment]
Have at least two interviews lined up for the remainder of this week. Let me know if any other relevant details have developed outside this issue and I'll otherwise proceed with the versions above and some details Emily and I chatted out.

**Comment by BLFiedler** [comment]
- **Interview 1:** Sound varies version. Clicks off the voltmeter during exploration, does not notice the sound change. Identifies a "a halo noise" whenever the lightbulb starts to turn on that gets louder as voltage increases/light bulb brighter. Does not identify the pitch change, until I ask her to directly compare the sound with the voltmeter on and off several times and to listen. "One noise is just solely for the lightbulb and now there's different higher-pitched sounds for the voltage" and maps the pitches to the direction. Since she did not understand the concept very well, she found herself using the sound more than the voltmeter, but guesses someone who knew more might use the visual more.

- **Interview 2:** Sound varies version. Notes "sound when lightbulb lights up", "one sound when it's positive, another note when it's negative and I think the volume of the sound is dependent on how much positive or negative it is" during exploration (unprompted) as well as noting the more coils make it "brighter" and louder in sound. When asked to specifically recall the sounds, she seems to have forgotten her previous relation between pitch and voltage direction and has trouble identifying any difference between the two conditions save for a "brightness" in the sound without the voltmeter. Tries to reason out that the voltmeter is having a similar effect to the difference between adding and removing a coil - "changing the distance". 

- **Interview 3:** Sound-does-not-vary version, then sound varies. Bit of an issue with Do Not Disturb on iPad and blocking sim sounds meant she plays awhile without sound prior to with sound. Quickly notes "It sounds like the sounds are different for positive and negative" and that it "sounds quieter" with the lower amplitude. Notes the usefulness of the click sound to indicate the voltage is maxed.

Misc notes:
- With the voltmeter on by default, participants seem to click it off and back on just to confirm the checkbox does something rather than investigating further.

- No one brings up the clanging during the sound recall question until prompted. Possibly just recognized as a sound that "belongs"/"makes sense"?

- There are no cue arrows on the magnet to indicate movement? Takes everyone a few pokes/clicks to find the interactable thing.
