### ISSUE TITLE
Magnet can go through the "borders" in all parts of sim

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/faradays-law#205]
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10

**Browser**
Chrome, Firefox

**Problem description**
This is for https://github.com/phetsims/QA/issues/581
When dragging the magnet around the borders of the sim, the magnet can go "through" the borders and become hidden and missing. 
The best way to do this is to hit downwards first and then to the right, but you can get through the borders through any part of the frame.

**Visuals**
This was on Firefox but I noticed on Chrome a bit as well. 
![faradayiframefirefox](https://user-images.githubusercontent.com/72031637/101091479-1251f300-356d-11eb-9a91-543f1aa98da4.gif)

I also noticed this on the sim itself, as well as the html download on Chrome, and on my Macbook Pro 10.13.6 as well. 

On sim:
![faradayborder](https://user-images.githubusercontent.com/72031637/101194914-7f1fc880-3613-11eb-868c-c9283776d5c9.gif)

On Legends of Learning:
![faradayLoL](https://user-images.githubusercontent.com/72031637/101194925-85ae4000-3613-11eb-89ff-aa33afc172aa.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Law‬
URL: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.1/phet/faradays-law_all_phet.html
Version: 1.4.0-rc.1 2020-12-02 22:52:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
Language: en-US
Window: 1707x818
Pixel Ratio: 2.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by brooklynlash** [comment]
This also happens in Firefox's Legends of Learning harness as well. I think it is an issue with the borders.

**Comment by brooklynlash** [comment]
This does not occur on the published sim or iframe.

**Comment by jbphet** [comment]
Nice catch @brooklynlash!

Here is an easier way to duplicate the problem, and the animated GIF below illustrates the sequence:

- Start with a freshly loaded sim.
- Drag the magnet to the bottom right corner.
- Continue dragging so that the mouse cursor is well below where the magnet is allowed to go in the vertical direction.
- Leaving the mouse cursor well below the magnet, very slowly move the magnet a little to the left, then back to the right.

In my screen capture I hit a debugger statement, but in 1.4.0-rc.1 you can get the magnet through the boundary pretty easily.  A similar process works in any corner.

![fl-magnet-escape](https://user-images.githubusercontent.com/3082831/101429680-bcf54900-38c0-11eb-94c5-1d864083344b.gif)

Here is what's going on: I rewrote most of the code related to having the magnet bump into things, and I missed the case where it is trying to move a little in one direction and a lot in the other at the very corners of the bounds.  I'll fix it.

**Comment by jbphet** [comment]
@KatieWoe and/or @brooklynlash - please test this on master and assign back to me with your results.

**Comment by brooklynlash** [comment]
Looks as if it is fixed on master! -- tested on Win 10 Chrome and Firefox

**Comment by jbphet** [comment]
Thanks @brooklynlash.  Unassigning until the next RC, where I'll have it tested.

**Comment by brooklynlash** [comment]
Sorry, reassigning again. On master now, you can completely slide through the magnet coils, I thought that was related so I am commenting about that here. 
![faradaycoil](https://user-images.githubusercontent.com/72031637/101517029-14350100-3935-11eb-9304-0b895a0d273b.gif)

**Comment by KatieWoe** [comment]
Good catch @brooklynlash 
I looked a bit myself, and wanted to note that this is different from https://github.com/phetsims/faradays-law/issues/195 as the speed of dragging or performance of the device does not matter, the boundary isn't even there in this case.

**Comment by brooklynlash** [comment]
Another thing to note: the sound effects still work as usual through the coils but the boundary is just not there

**Comment by jbphet** [comment]
Oops.  I clearly blew my regression testing.  Fixed now, please have another go at it on master.

**Comment by brooklynlash** [comment]
Works now on master

**Comment by KatieWoe** [comment]
Noting here that I saw this on iPad Safari.

**Comment by jbphet** [comment]
The fixes for this issue have now been cherry-picked to the 1.4 release branch.

**Comment by phet-steele** [comment]
This looks good for me in 1.4.0-rc.2!
