### ISSUE TITLE
Possible to pass magnet through the vertical bounds of the solenoid

### ISSUE THREAD

**Issue by bryo5363** [phetsims/faradays-law#47]
By dragging the magnet with a significant velocity it is possible to pass the magnet through the vertical bounds of the solenoid. 

When trying this on the Java simulation I experienced very strange behavior; dragging the magnet in the Java sim has significantly worse performance than the HTML version

**Comment by jbphet** [comment]
The solution that @MDmitrieva implemented many years ago has served us well on this sim until now.  However, because the solution was to adjust various bounds by 1 screen coordinate in several places, this was causing issues with detecting collisions between the magnet and the restricted bounds, and we needed to correctly detect these collisions in order to produce sound.  I've backed out the bounds adjustments, and will continue to make improvements to the drag behavior, but future commits will be referenced only to issue #195 and not this one.
