### ISSUE TITLE
Artifacts present in Firefox

### ISSUE THREAD

**Issue by bryo5363** [phetsims/faradays-law#48]
Test device: MacBook Pro

Operating System: 10.9.5

Browser: Firefox 32.0.3

Problem description: Artifacts present in Firefox

Steps to reproduce:
-Open Sim (iFrame applicable too)
-Drag the magnet slowly
-Artifacts will be present
Severity:

Screenshots:
![screen shot 2014-10-07 at 12 13 46 pm](https://cloud.githubusercontent.com/assets/7717368/4547561/2e2584dc-4e4e-11e4-9fdb-a782d1cde7fa.png)

Troubleshooting information (do not edit):
Name: Faraday's Law
URL: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.0.0-rc.1/faradays-law_en.html
Version: 1.0.0-rc.1
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0
Language: en-US
Window: 1280x603
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
I just tried this on v1.0.2, and no artifacts are seen.  Either @jonathanolson's fix took care of it or Firefox has improved since this was last tested.

Testing was on OSX 10.11, Firefox 41.0.1

Details from the "Report a problem" menu item:

Troubleshooting information (do not edit):
Name: Faraday's Law
URL: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.0.2/faradays-law_en.html
Version: 1.0.2
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:41.0) Gecko/20100101 Firefox/41.0
Language: en-US
Window: 1207x585
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
Issue appears to be resolved, closing.

**Comment by samreid** [comment]
@jonathanolson do you think we still need the extra padding workaround, or can it be removed now?

**Comment by jonathanolson** [comment]
Don't know, would ask @ariel-phet whether this warrants some QA testing to see if we can remove.

**Comment by ariel-phet** [comment]
@samreid maybe try removing, and doing a quick sanity check on latest firefox? If it looks good, ask @phet-steele  if he can take 15 minutes to confirm on FF.

**Comment by samreid** [comment]
Thanks, #91 is another FF-related rendering issue I'd like to test at the same time, I should publish a dev version with both changes.

**Comment by samreid** [comment]
After removing the workaround, the built version iframe doesn't show artifacts on Mac/Firefox 57.0

![image](https://user-images.githubusercontent.com/679486/33086031-b1d90302-cea3-11e7-9040-65dd3474d394.png)

I'll commit and push soon.

**Comment by samreid** [comment]
@phet-steele can you test this issue in https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-dev.6/faradays-law_en.html particularly on some firefoxes?

**Comment by phet-steele** [comment]
I don't see artifacts on anything when using FF 57
