### ISSUE TITLE
Voltmeter appears to be going the wrong way

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/faradays-law#65]
One of our users pointed out that he believes the voltmeter is going the wrong way in the simulation. I looked at his argument, and I believe he is correct. Need @dubson to also take a look

![explain](https://cloud.githubusercontent.com/assets/4051174/8678638/d8c1dd78-2a12-11e5-865e-dadfbf6d5ff5.png)

**Comment by dubson** [comment]
The user is correct!  We have the voltage polarity wrong in the published sim! Published sim should be corrected as soon as possible.

**Comment by ariel-phet** [comment]
@jbphet - possible to publish a maintenance release for this fix, or should we wait to redeploy? (could be one of the next sims on the redeploy docket)

**Comment by jbphet** [comment]
Since the behavior is blatantly incorrect, I think a quick maintenance release is warranted.  This sim is one of the four instrumented sims, so a full new version should be tested pretty thoroughly, which may take some time.  IMO, it's better to fix the inaccuracy immediately and then publish the new release when appropriate.

**Comment by ariel-phet** [comment]
Thanks for the assessment @jbphet - please go ahead with a maintenance release!

**Comment by jbphet** [comment]
I have deployed version 1.0.2 to the main site.  I did the dev testing myself, since this was literally a one-character change (excluding some comment editing), and went forward with the production deployment.  I did the deployment manually due to complications with using ```grunt deploy-production```, and it appears that the version shown on the sim page didn't get properly updated (see screen shot below).  I'm going to assign this issue to @aaronsamuel137 so that he can fix up the version number and anything else that isn't handled when manual deployments are done.

![faraday-web-version](https://cloud.githubusercontent.com/assets/3082831/8940847/52fb6a98-3529-11e5-805a-9ff18c012db2.png)

**Comment by jbphet** [comment]
@aaronsamuel137 - once fixed, feel free to close this.

**Comment by aaronsamuel137** [comment]
Updated on the main site now. A few comments:

1. grunt deploy-production currently deployed to phet-dev since it is still being tested.
2. you can update the version number in the admin section of the website under "projects". Note that html projects all begin with "html/". Pressing "synchronize now" will automatically update to the latest version. Once the build server is deployed it will automatically synchronize.

Closing

**Comment by jessegreenberg** [comment]
In a11y meeting on 3/2/18 the IDRC pointed out that the needle on the Voltmeter goes in the opposite direction as the deployed version (currently 1.1.10). Reopening.

Deployed version behaves like 1.0.2 from https://github.com/phetsims/faradays-law/issues/65#issuecomment-125722930 so I assume master is incorrect.

@ariel-phet can you please review and assign to a developer?

**Comment by ariel-phet** [comment]
Verified that master appears to be incorrect on 3/5/2018

@samreid can you correct this behavior? Maybe look at @jbphet commit above?

**Comment by samreid** [comment]
I confirmed that the website version has the needle move to the left (negative) as you approach the coils from the right, and master has the needle move to the right (positive) as you approach the coils from the right.

**Comment by samreid** [comment]
15 minutes of looking did not uncover the cause of this problem, but I flipped the sign and the behavior appears to be OK in master now.  @ariel-phet do you want more time spent trying to understand what caused this problem?  Can you double check master on phettest that the behavior is now correct?

**Comment by ariel-phet** [comment]
@samreid - double checked on Master. Looks good. Closing.

**Comment by ariel-phet** [comment]
@samreid no need to spend more time.
